export const rewardifySubOptionsObj = {
    "Copuon Based": [
      { key: 1, taken: false, value: "Static Coupon System" },
      { key: 2, taken: false, value: "Dynamic Coupon System" },
      { key: 3, taken: false, value: "Coupon integrated with API" },
      { key: 4, taken: false, value: "Redeem  coupon Integrated with Website" },
      { key: 5, taken: false, value: "Wallet System for coupon storage " },
    ],
    "Points System": [
      { key: 1, taken: false, value: "Category/Product based point", },
      { key: 2, taken: false, value: "Single Product Info with point claim" },
      { key: 3, taken: false, value: "Multiple product scan with point claim" },
      { key: 4, taken: false, value: "Wallet for points" },
      { key: 5, taken: false, value: "Reedemption feature" },
      { key: 6, taken: false, value: "Earn/Redeem passbook history" },
      { key: 7, taken: false, value: "Gift Catalogue" },
      { key: 8, taken: false, value: "Dynamic Gift Catalogue System" },
      { key: 9, taken: false, value: "Onetime Gift Catalogue System" },
      { key: 10, taken: false, value: "Redeem Cart selection feature" },
      { key: 11, taken: false, value: "Gift Delivery Status" },
    ],
    Cashback: [
      { key: 1, taken: false, value: "Cash amount popup" },
      { key: 2, taken: false, value: "Profile Confirmation" },
      { key: 3, taken: false, value: "Payment method Confirmation" },
      { key: 4, taken: false, value: "Bank account system" },
      { key: 5, taken: false, value: "UPI System" },
      { key: 6, taken: false, value: "Paytm System" },
      { key: 7, taken: false, value: "Payment summery visibility" },
    ],
    Wheel: [
      { key: 1, taken: false, value: "Wheel on Dashboard" },
      { key: 2, taken: false, value: "Wheel on Menu" },
      { key: 3, taken: false, value: "Wheel items setup onetime" },
      { key: 4, taken: false, value: "Wheel item dynamic setup" },
      { key: 5, taken: false, value: "Gift Based Wheel" },
      { key: 6, taken: false, value: "Cash Based Wheel" },
      { key: 7, taken: false, value: "Mixed (Gift/Cash) Based Wheel" },
      { key: 8, taken: false, value: "Location Based wheel" },
      { key: 9, taken: false, value: "User based wheel" },
      { key: 10, taken: false, value: "Scanning Based wheel" },
      { key: 11, taken: false, value: "Day/month/time Based Wheel" },
    ],
    "Scan & Win": [
      { key: 1, taken: false, value: "Win Item Popup" },
      { key: 2, taken: false, value: "Win item list" },
      { key: 3, taken: false, value: "Claim win item list" },
      { key: 4, taken: false, value: "History of win/claim" },
      { key: 5, taken: false, value: "Win Item Confirmation" },
      { key: 6, taken: false, value: "Gift Delivery Status" },
    ],
  };