export const dynamicForm = {
    template_name:"QuikLinx Template 1",
    industry_type:1,
    template_type:0,
    product_name:false,
    product_description:false,
    product_image:false,
    product_code:false,
    customer_name:false,
    customer_number:false,
    customer_email:false,
    customer_address:false,
    product_serial:false,
    qr_code:false,
    date_of_purchase:false,
    company_customer_care_no: false,
    company_customer_care_email:false,
    points_redeemed:false,
    points_redeemed_value:30,
    gift_redeemed:false,
    gift_redeemed_value:10,
    gift_details:{},
    mpin_reset:false,
    mpin_set:false,
    profile_update:false,
    insufficient_point:false,


  };

